Задание 6. Добавить функциональность регистрации пользователя
gpb-it-factory/korshunov-telegram-bot pull request #10
Opened 2024-05-28 13:23 UTC by nosopirochka

2024-06-04 06:22 UTC, vaganov-vadim requested changes
Привет! В целом здорово, но есть места для улучшений, постарался подробно их отметить. Давай попробуем ещё прокачать наше решение. Если будут вопросы по написанному - обращайся тут или в тг :)

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/TelegramBot.java
> +public final class TelegramBot extends TelegramLongPollingBot {
Лайк за final :)

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/TelegramBot.java
> +    private MessageSender messageSender;
Давай лучше пользоваться constructor injection. У field-injection есть минусы, см. https://www.baeldung.com/java-spring-field-injection-cons

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/TelegramBot.java
> +    private CommandMaker commandMaker;
Аналогично как и выше.

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +    public CommandMaker(Start start, Ping ping, Register register) {
Здесь видится небольшой антипаттерн - получается нам, чтобы добавить новую команду, нужно всегда добавлять её в конструктор и постоянно менять код этого класса. Давай вспомним про Open-Closed Principle и попробуем это как-то развязать.  Например, у тебя есть класс Command, мы можем использовать эту абстракцию, чтобы как-то обобщить работу с командами. Если нужен будет совет - пиши :)

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
>          return switch (commandString) {
Здесь также, как и в комменте выше, если несколько человек будет работать над этим кодом одновременно, то это будет местом для множества конфликтов. Может, нам как-то инкапсулировать команду и выполняемую работу после вызова этой команды в одну сущность?

2024-06-04 06:22 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Register.java
> +        return new RestTemplate().postForEntity(path, entity, String.class);
Более удачно было бы вынести этот клиент как отдельную абстракцию. Так проще как минимум тестировать решение. Также создавать RestTemplate каждый раз выглядит избыточным. Напрашивается абстракция и бин к ней, под копотом которой уже необходимый тебе клиент :)

2024-06-04 06:22 UTC, vaganov-vadim commented on src/test/java/com/gpb/minibank/service/commandMaker/commands/CommandsTests.java
> +    void testPing() {
Мне нравится, что тесты сосредотачиваются именно на поведении, а не на деталях инфраструктуры, это здорово!
Если немного поправить подход к http-вызовам (отметил в комменте выше), то подобный тест тоже будет легко написать, попробуй, пожалуйста.

2024-06-04 13:54 UTC, nosopirochka commented
Вадим, привет!
Подскажи, пожалуйста.
Я ведь правильно понимаю из спецификации, что это по сути описание взаимодействия middle слоя и backend слоя? И, как будет взаимодействовать middle и frontend мы уже решаем сами. Верно?
Или под бэкендом мы подразумеваем middle слой в данной спецификации?

2024-06-04 15:22 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +    public CommandMaker(Start start, Ping ping, Register register) {
Построил работу моего CommandMaker на поиске в стриме нужного метода, но пришлось передавать ненужный update в команду /ping, чтобы дополнительную проверку не делать именно для этого метода. Ничего? (не думаю, что ничего, так как передаю по сути ненужные для метода данные с: ) Или же лучше сделать дополнительную проверку для него в случае, если Optional пустой будет?

2024-06-11 05:38 UTC, vaganov-vadim commented
> Вадим, привет! Подскажи, пожалуйста. Я ведь правильно понимаю из спецификации, что это по сути описание взаимодействия middle слоя и backend слоя? И, как будет взаимодействовать middle и frontend мы уже решаем сами. Верно? Или под бэкендом мы подразумеваем middle слой в том числе в данной спецификации? Спрашиваю потому, что я ловлю на фронтенде свой Error при ошибке, который из себя представляет message и статус код, но не Error, который из четырёх полей состоит. Но некоторые ребята, я заметил, пробрасывают в качестве респонса Error, который в спецификации дан. То есть буквально понимают, что с миддла должны прийти данные, которые в спецификации даны, хотя вроде как спецификация именно по бэкенду дана, то есть по третьему слою.

Привет. Всё верно, в спецификации взаимодействие с backend. Как будут общаться telegram и middle, в том числе формат ошибок и всё остальное - решать вам. Я бы ошибку из backend напрямую пользователю не прокидывал, это плохой паттерн, т. к. она может быть нечитаемая, специфическая, или содержать данные, которые пользователю знать не нужно.

2024-06-11 05:55 UTC, vaganov-vadim requested changes
Привет! Улучшений масса, это радует, стало прям круче. Оставил ещё несколько комментов - давай их проработаем.

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Command.java
> +    String getNameOfCommand();
По сути немного избыточный нейминг. command.getNameOfCommand() семантически равно command.getName(), я бы сделал покороче, чтобы не повторяться.

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +public final class CommandMaker {
Может быть тоже придирка, но по названию не совсем понятно, что класс делает. Может, он больше какой-то Finder? Или Matcher?) Некритично, но вероятно можно найти более говорящее название.

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +    private final RestTemplate restTemplate;
Кстати, Спринг уже не рекомендуется использовать RestTemplate, посмотри в сторону RestClient.

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +    public ResponseEntity<String> runRequest(Update update) {
Мне кажется, что этот метод сейчас очень завязан на телеграм. Может, нам отвязаться от Update и просто прокидывать нужные данные сюда в виде другой модели?

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +        return restTemplate.postForEntity(path, entity, String.class);
Мы разве не ожидаем получить конкретную модельку? Или пока не продумывал?

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +public final class RegisterRequestRunner {
Т. к. эта сущность взаимодействует с "внешним миром", то мы можем вынести его как интерфейс - тогда будет и тестировать проще, и подстраиваться под изменения - вдруг интеграция уедет куда-нибудь на Kafka. Нам важен контракт, а не сама реализация.

2024-06-11 05:55 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +    public ResponseEntity<String> runRequest(Update update) {
По сути должен быть контракт вроде public ResponseEntity<RegisterResponseDTO> register(CreateUserDTO dto). Над неймингом сам подумай :)

2024-06-11 20:28 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +        return restTemplate.postForEntity(path, entity, String.class);
Я планировал ничего в бади не возвращать, Вадим. А по факту получения 204 кода отдавать сообщение об успешной регистрации юзеру. Если эксепшн возвращается, то генерирую сообщение с текстом ошибки (по типу "Вы уже зарегистрированы", которая сейчас с миддла у меня возвращается), которое в бади получаю

2024-06-11 21:44 UTC, nosopirochka commented
Привет, Вадим!
Прочти, пожалуйста, комментарии к конверсэйшенам (их два).
Заранее спасибо)

2024-06-12 13:45 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +        return restTemplate.postForEntity(path, entity, String.class);
Изменил, сейчас в РестКлиенте собираю из ответа BodylessEntity, а потом смотрю, какой код вернулся

2024-06-13 05:34 UTC, vaganov-vadim approved these changes
Привет! Всё стало прямо сильно круче, молодец. Даю аппрув, но оставил один коммент, посмотри его пост-фактум, пожалуйста.

2024-06-13 05:34 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandHandler/commands/clients/registerClient/RegisterClient.java
> +    ResponseEntity<?> runRequest(CreateUserDTO createUserDTO);
А ResponseEntity<Void> нельзя тут сделать? Просто <?> - скорее антипаттерн.

2024-06-13 05:34 UTC, vaganov-vadim commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/requestRunner/RegisterRequestRunner.java
> +        return restTemplate.postForEntity(path, entity, String.class);
Да, всё ок!

2024-06-13 09:13 UTC, merged