Задание 2. Добавлен README
gpb-it-factory/korshunov-telegram-bot pull request #2
Opened 2024-05-06 16:46 UTC by nosopirochka

2024-05-07 14:26 UTC, vaganov-vadim requested changes
Понравился креатив! Но давай схемку перерисуем. Всё же это был пример, а не реализация конкретно этого сервиса.

2024-05-07 14:26 UTC, vaganov-vadim commented on README.md
> +![logo](pictures/logo.png)
Лого - супер :)

2024-05-07 14:26 UTC, vaganov-vadim commented on README.md
> +@startuml diagram
Эта схемка была примером :) Всё же взамодействие между нашими компонентами будет слегка другое, давай отрисуем как Frontend взаимодействует с пользователем и другими сервисами.

2024-05-07 14:28 UTC, vaganov-vadim commented on README.md
> +GPB мини-банк
Не к README - бонусом. .idea лучше добавить в .gitignore, локальные настройки IDEA в репозитории не нужны.

2024-05-08 07:35 UTC, nosopirochka commented on README.md
> +![logo](pictures/logo.png)
Спасибо :)

2024-05-08 07:36 UTC, nosopirochka commented on README.md
> +@startuml diagram
Не очень внимательно на схемку посмотрел, которая была дана (бот(frontend-level) -> middle-level -> backend-level). Не столько срисовал с примера, сколько сам представил это именно так. Всё понял. Исправлю :)

2024-05-08 07:36 UTC, nosopirochka commented on README.md
> +GPB мини-банк
Ок. Докину .gitignore

2024-05-13 16:42 UTC, vaganov-vadim approved these changes
Аппрув, можно вливать =)

2024-05-14 12:47 UTC, merged