Задание 2. Создан 'скелет' бота
gpb-it-factory/korshunov-telegram-bot pull request #4
Opened 2024-05-16 14:31 UTC by nosopirochka

Создан "скелет" бота
Обновлён README (добавлен раздел Quick Start)
Обновлён .gitignore

2024-05-20 08:00 UTC, konstantin-kozlovskiy requested changes
Необходимо исправить замечания

2024-05-20 08:00 UTC, konstantin-kozlovskiy commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +            var result = command.exec();
Странное поведение, не так ли? зачем выполнять wrong command?:)

2024-05-20 08:00 UTC, konstantin-kozlovskiy commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Pink.java
> +public class Pink implements Command {
Ping

2024-05-20 08:00 UTC, konstantin-kozlovskiy commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Pink.java
> +        return "ponk";
Pong

2024-05-20 08:00 UTC, konstantin-kozlovskiy commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Start.java
> +                + "\n\nЯ умею выполнять команду /pink."
/ping и везде далее по тексту

2024-05-20 14:04 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +            var result = command.exec();
Я же с интерфейсом работаю. А раз есть интерфейс, то я подумал, что его можно было было использовать в свиче, и добавить помимо других команд команду-ошибку. Иначе ведь интерфейс особо и не нужен, а с ним можно было бы так интересно сыграть. А с интерфейсом и расширяться вроде бы проще: как добавлять новые команды, так и расширить сам интерфейс в случае необходимости.

2024-05-20 14:16 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +            var result = command.exec();
Переписал. Получилось меньше кода. Интерфейс пока что оставил, ничего?
Меньше кода - лучше :smile:

2024-05-20 18:35 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/CommandMaker.java
> +            var result = command.exec();
По поводу того, что оставил интерфейс. Позже, я думаю, видно будет, как это лучше всего будет выглядеть и реализовать определённым образом. То есть, когда над middle уровнем работа начнётся

2024-05-20 18:37 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Pink.java
> +public class Pink implements Command {
изменено

2024-05-20 18:37 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Pink.java
> +        return "ponk";
изменено

2024-05-20 18:37 UTC, nosopirochka commented on src/main/java/com/gpb/minibank/service/commandMaker/commands/Start.java
> +                + "\n\nЯ умею выполнять команду /pink."
изменено

2024-05-20 21:18 UTC, nosopirochka reviewed
изменено

2024-05-23 05:26 UTC, konstantin-kozlovskiy approved these changes

2024-05-23 08:52 UTC, merged